time_step: 0.025
step_knots: 31
support_knots: 8

max_iterations: 1000
num_threads: 4

lleg: LLEG_LINK5
rleg: RLEG_LINK5
root: BODY

initial_configuration: [0, 0, 0.91065,                                                    # position
                        0, 0, 0, 1.0,                                                     # root orientation
                        0, 0, 0,                                                          # chest
                        0, 0,                                                             # head
                        0, 0.698132, 0.349066, 0.087266, -1.39626, 0, 0, -0.349066, 0,    # larm
                        0, 0.698132, -0.349066, -0.087266, -1.39626, 0, 0, -0.349066, 0,  # rarm
                        0.000128, -0.002474, -0.488869, 1.01524, -0.526374, 0.002474,     # lleg
                        0.000128, -0.002474, -0.488908, 1.01524, -0.526335, 0.002474]     # rleg

x_weights: [0.0, 0.0, 0.0, 10000.0, 10000.0, 10000.0,                                 # root
            10000.0, 10000.0, 10000.0,                                                # chest
            10000.0, 10000.0,                                                         # head
            1000.0, 1000.0, 1000.0, 1000.0, 1000.0, 1000.0, 1000.0, 1000.0, 1000.0,   # larm
            1000.0, 1000.0, 1000.0, 1000.0, 1000.0, 1000.0, 1000.0, 1000.0, 1000.0,   # rarm
            0.01, 0.01, 0.01, 100.0, 0.01, 0.01,                                      # lleg
            0.01, 0.01, 0.01, 100.0, 0.01, 0.01,                                      # rleg
            10.0, 10.0, 10.0, 10.0, 10.0, 10.0,                                       # root
            10.0, 10.0, 10.0,                                                         # chest
            10.0, 10.0,                                                               # head
            10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0,                     # larm
            10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0,                     # rarm
            10.0, 10.0, 10.0, 10.0, 10.0, 10.0,                                       # lleg
            10.0, 10.0, 10.0, 10.0, 10.0, 10.0]                                       # rleg

control_weight: 0.1
com_track_weight: 100000
foot_track_weight: 100000
